# Generated by Django 2.1.1 on 2018-09-19 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_auto_20180919_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='order_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.order'),
        ),
    ]
