# Generated by Django 2.1.1 on 2018-09-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_auto_20180919_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='bill_check_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
