# Generated by Django 2.1.1 on 2018-09-19 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20180919_2258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company_bill',
            options={'verbose_name': '公司资金流水', 'verbose_name_plural': '公司资金流水'},
        ),
        migrations.AddField(
            model_name='company_bill',
            name='finance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.finance_unit', verbose_name='处理人'),
        ),
        migrations.AlterField(
            model_name='company_bill',
            name='affair',
            field=models.CharField(max_length=20, verbose_name='事件'),
        ),
        migrations.AlterField(
            model_name='company_bill',
            name='bill_id',
            field=models.CharField(max_length=20, verbose_name='流水号'),
        ),
        migrations.AlterField(
            model_name='company_bill',
            name='profit',
            field=models.IntegerField(default=1000, verbose_name='收入'),
        ),
    ]
