# Generated by Django 2.1.1 on 2018-09-20 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_auto_20180920_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cash_unit',
            name='cash_name',
            field=models.CharField(max_length=10, verbose_name='员工姓名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_balance',
            field=models.IntegerField(default=100),
        ),
    ]
