# Generated by Django 2.1.1 on 2018-09-20 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_auto_20180920_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='cashier_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurant.cash_unit'),
        ),
    ]
