# Generated by Django 2.1.1 on 2018-09-20 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_auto_20180920_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_bill',
            name='company_balance',
            field=models.FloatField(default=100000),
        ),
    ]
